### ISSUE TITLE
مشکل در راه انداری

### ISSUE THREAD

**Issue by omidraha852** [xmohammad1/Waterwall-RRT#4]
سلام درود
سپاس از زحماتتون
بعد از ران کردن اسکریپت و انجام مراحل خواسته شده توی اسکریپت برای هر دو سرور داخل و خارج و اتمام تانل برقرار نمیشه
ممنون میشم بیشتر توضیح بدین خیلی گنگ و گیج 
کننده هستش 
 من به این صورت مراحل رو میرم
۱-ران کردن اسکریپت
۲-وارد کردن موارد خواسته شده توسط اسکریپت
۳-اجرای دستور ./waterwall
 که با خطای no such file or directory مواجه میشم
توی سرور هم فایلهای json توی شاخه /root/RRT ساخته شدن

**Comment by xmohammad1** [comment]
خودش ران میکنه لازم نیست شما ران کنید
اگه تانل برقرار نمیشه دلیلش اشتباه وارد کردن یکی از موارد میتونه باشه

**Comment by omidraha852** [comment]
> خودش ران میکنه لازم نیست شما ران کنید اگه تانل برقرار نمیشه دلیلش اشتباه وارد کردن یکی از موارد میتونه باشه

بله مشکل از بنده بود الان متصل شد
ولی توی پینگ گرفتن هر 2 الی سه تا پینگی که مگیرم هندشیک تایم اوت میده ولی کانفیگ متصل هست
ممنون میشم راهنمایی بفرمایید

**Comment by xmohammad1** [comment]
فعلا یه سری باگ ها وجود داره که سازنده core گفته در اپدیت بعدی درستشون میکنه
